### ISSUE TITLE
Find permanent proxy solution.

### ISSUE THREAD

**Issue by pfmephisto** [linkarkitektur/SpeckleLCA#6]
Turns out for `https://cors-anywhere.herokuapp.com/`
A trial need to be requested.

**Comment by eljoelopez** [comment]
https://cors-anywhere.herokuapp.com/corsdemo

for anyone if prompted for not token access to LCAbyg

After requested demo, cleared cache and reload it should work

**Comment by pfmephisto** [comment]
We should add an alert message telling people to to to 
`cors-anywhere.herohuapp.com` and request a trial. 
This should be a simple workaround for now.

**Comment by pfmephisto** [comment]
Temporary fix: 45978a3253d347b38822be70bbffebfbb7198829
